services:
  # Base de datos SQL Server
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: transferencia-automotor-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TransferApp2024!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - transferencia-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Aplicación NestJS (solo para producción)
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: transferencia-automotor-app
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=1433
      - DB_USERNAME=sa
      - DB_PASSWORD=TransferApp2024!
      - DB_DATABASE=TransferenciaAutomotor
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - transferencia-network
    profiles:
      - prod

volumes:
  db_data:
    driver: local

networks:
  transferencia-network:
    driver: bridge
