version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: transferencia-automotor-db-dev
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TransferApp2024!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - db_dev_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - transferencia-network

volumes:
  db_dev_data:

networks:
  transferencia-network:
    driver: bridge
