import { Injectable } from '@nestjs/common';
import { FormFieldRepositoryPort } from 'src/forms/domain/ports/form-field-repository.port';

@Injectable()
export class FormFieldSeedService {
  constructor(private readonly formFieldRepository: FormFieldRepositoryPort) {}

  async seedFormFields(): Promise<void> {
    console.log('🌱 Verificando campos de formularios en base de datos...');

    try {
      // Eliminar campos existentes para recrearlos con la configuración actualizada
      const existingFields = (await this.formFieldRepository.findAll?.()) || [];
      if (existingFields.length > 0) {
        console.log('🗑 Eliminando campos existentes para actualizar...');
        for (const field of existingFields) {
          await this.formFieldRepository.delete?.(field.id);
        }
      }

      console.log('🌱 Poblando campos de formularios actualizados...');

      await this.createVehicleRegistrationFields();
      await this.createVehicleTransferFields();

      console.log('✅ Campos de formularios insertados exitosamente');
    } catch (error) {
      console.error('❌ Error al insertar campos:', error);
    }
  }

  private async createVehicleRegistrationFields(): Promise<void> {
    const fields = [
      // Datos Básicos del Vehículo
      {
        formId: 'vehicle-registration',
        name: 'patente',
        type: 'plate',
        label: 'Dominio (Patente)',
        description: 'ATR_DOMINIO - Patente del vehículo a registrar',
        placeholder: 'AA111AA o AAA111',
        required: true,
        orderIndex: 1,
        help: 'Ingrese la nueva patente asignada al vehículo',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({
          customValidation: 'validateNewPlate',
        }),
        eventsConfig: JSON.stringify({
          onValidation: {
            action: 'both',
            endpoint: 'automotor/consultar',
            fields: {
              modelo_descripcion: 'modelo',
              codigo_alta: 'codigoAlta',
              codigo_alta_descripcion: 'codigoAltaDescripcion',
              registro_automotor: 'registroId',
              registro_descripcion: 'registroDescripcion',
              fecha_alta_vehiculo: 'fechaAlta',
              fecha_inicio_vigencia: 'fechaVigencia',
              anio_fabricacion: 'anioFabricacion',
              marca_descripcion: 'marca',
              tipo_rnpa_descripcion: 'tipoDescripcion',
              valor_vehiculo: 'valorVigente',
            },
            debounceTime: 500,
          },
        }),
      },
      {
        formId: 'vehicle-registration',
        name: 'tipo_vehiculo',
        type: 'select',
        label: 'Tipo de Vehículo',
        description: 'ATR_PTH_ID - Clasificación del tipo de vehículo',
        required: true,
        orderIndex: 2,
        help: 'Seleccione el tipo de vehículo según clasificación del registro',
        fieldConfig: JSON.stringify({
          options: [
            { id: 'automovil', label: 'Automóvil' },
            { id: 'motocicleta', label: 'Motocicleta' },
            { id: 'camion', label: 'Camión' },
            { id: 'camioneta', label: 'Camioneta' },
            { id: 'colectivo', label: 'Colectivo' },
            { id: 'remolque', label: 'Remolque' },
            { id: 'semirremolque', label: 'Semirremolque' },
            { id: 'tractor', label: 'Tractor' },
            { id: 'maquinaria_especial', label: 'Maquinaria Especial' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'anio_fabricacion',
        type: 'number',
        label: 'Año de Fabricación',
        description: 'ATR_FECHA_FABRICACION - Año de fabricación del vehículo',
        placeholder: '2024',
        required: true,
        orderIndex: 3,
        help: 'Año de fabricación según documentación del fabricante',
        fieldConfig: JSON.stringify({
          min: 1900,
          max: 2030,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'origen_rnpa',
        type: 'radio',
        label: 'Origen RNPA',
        description: 'ATR_ORIGEN_RNPA - Origen del vehículo según RNPA',
        required: true,
        orderIndex: 4,
        help: 'Determina si el vehículo es de origen nacional o importado',
        fieldConfig: JSON.stringify({
          options: [
            { id: 'nacional', label: 'Nacional' },
            { id: 'importado', label: 'Importado' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'color_vehiculo',
        type: 'select',
        label: 'Color Principal',
        description: 'Color principal del vehículo',
        required: true,
        orderIndex: 5,
        fieldConfig: JSON.stringify({
          options: [
            { id: 'blanco', label: 'Blanco' },
            { id: 'negro', label: 'Negro' },
            { id: 'gris', label: 'Gris' },
            { id: 'azul', label: 'Azul' },
            { id: 'rojo', label: 'Rojo' },
            { id: 'verde', label: 'Verde' },
            { id: 'amarillo', label: 'Amarillo' },
            { id: 'marron', label: 'Marrón' },
            { id: 'bordo', label: 'Bordó' },
            { id: 'violeta', label: 'Violeta' },
            { id: 'plateado', label: 'Plateado' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'numero_motor',
        type: 'text',
        label: 'Número de Motor',
        description: 'ATR_MOTOR - Número identificatorio del motor',
        required: true,
        orderIndex: 6,
        help: 'Número grabado en el motor del vehículo',
        fieldConfig: JSON.stringify({
          maxLength: 50,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'numero_chasis',
        type: 'text',
        label: 'Número de Chasis/VIN',
        description: 'ATR_CHASIS - Número identificatorio del chasis',
        required: true,
        orderIndex: 7,
        help: 'Número de chasis o VIN del vehículo',
        fieldConfig: JSON.stringify({
          maxLength: 50,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'fecha_primera_inscripcion',
        type: 'date',
        label: 'Fecha de Primera Inscripción',
        description:
          'ATR_FECHA_ALTA - Fecha de primera inscripción del vehículo',
        required: true,
        orderIndex: 8,
        help: 'Fecha en que se realiza la primera inscripción',
        defaultValue: '{{ today }}',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'marca_rnpa',
        type: 'text',
        label: 'Código Marca RNPA',
        description: 'ATR_ID_MARCA_RNPA - Código de marca según RNPA',
        required: true,
        orderIndex: 9,
        help: 'Código de marca asignado por el RNPA',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({
          customValidation: 'validateRnpaCode',
        }),
        eventsConfig: JSON.stringify({
          onValidation: {
            action: 'both',
            endpoint: 'forms/autocomplete',
            requestBody: {
              endpoint: 'PAR_MARCAS_RNPA',
              value: '{{ field_value }}',
              context: {
                table: 'par_marcas_rnpa',
                searchField: 'codigo_marca',
              },
            },
            fields: {
              marca_descripcion: 'descripcion',
            },
            debounceTime: 500,
          },
        }),
      },
      {
        formId: 'vehicle-registration',
        name: 'marca_descripcion',
        type: 'text',
        label: 'Marca del Vehículo',
        description: 'Descripción de la marca del vehículo',
        readonly: true,
        orderIndex: 10,
        help: 'Se completa automáticamente al ingresar el código de marca',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'tipo_rnpa',
        type: 'text',
        label: 'Código Tipo RNPA',
        description: 'ATR_ID_TIPO_RNPA - Código de tipo según RNPA',
        required: true,
        orderIndex: 11,
        help: 'Código de tipo de vehículo según RNPA',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({
          customValidation: 'validateRnpaCode',
        }),
        eventsConfig: JSON.stringify({
          onValidation: {
            action: 'both',
            endpoint: 'forms/autocomplete',
            requestBody: {
              endpoint: 'PAR_TIPOS_RNPA',
              value: '{{ field_value }}',
              context: {
                table: 'par_tipos_rnpa',
                searchField: 'codigo_tipo',
              },
            },
            fields: {
              tipo_rnpa_descripcion: 'descripcion',
            },
            debounceTime: 500,
          },
        }),
      },
      {
        formId: 'vehicle-registration',
        name: 'tipo_rnpa_descripcion',
        type: 'text',
        label: 'Tipo de Vehículo RNPA',
        description: 'Descripción del tipo de vehículo según RNPA',
        readonly: true,
        orderIndex: 12,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'modelo_rnpa',
        type: 'text',
        label: 'Código Modelo RNPA',
        description: 'ATR_PMO_ID - Código del modelo según RNPA',
        required: true,
        orderIndex: 13,
        help: 'Código del modelo asignado por el RNPA',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({
          customValidation: 'validateRnpaCode',
        }),
        eventsConfig: JSON.stringify({
          onValidation: {
            action: 'both',
            endpoint: 'forms/autocomplete',
            requestBody: {
              endpoint: 'PAR_MODELOS_RNPA',
              value: '{{ field_value }}',
              context: {
                table: 'par_modelos_rnpa',
                searchField: 'codigo_modelo',
                filterBy: {
                  marca_id: '{{ marca_rnpa }}',
                  tipo_id: '{{ tipo_rnpa }}',
                },
              },
            },
            fields: {
              modelo_descripcion: 'descripcion',
            },
            debounceTime: 500,
          },
        }),
      },
      {
        formId: 'vehicle-registration',
        name: 'modelo_descripcion',
        type: 'text',
        label: 'Modelo del Vehículo',
        description: 'L_PMO_PMO_DESCRIPCION - Descripción del modelo',
        readonly: true,
        orderIndex: 14,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'version_modelo',
        type: 'text',
        label: 'Versión del Modelo',
        description: 'Versión específica del modelo del vehículo',
        orderIndex: 15,
        help: 'Ej: LT, LTZ, Titanium, etc.',
        fieldConfig: JSON.stringify({
          maxLength: 100,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'combustible',
        type: 'select',
        label: 'Tipo de Combustible',
        description: 'Tipo de combustible del vehículo',
        required: true,
        orderIndex: 16,
        fieldConfig: JSON.stringify({
          options: [
            { id: 'nafta', label: 'Nafta' },
            { id: 'diesel', label: 'Diesel' },
            { id: 'gnc', label: 'GNC (Gas Natural Comprimido)' },
            { id: 'electrico', label: 'Eléctrico' },
            { id: 'hibrido', label: 'Híbrido' },
            { id: 'flex', label: 'Flex (Nafta/Etanol)' },
            { id: 'hidrogeno', label: 'Hidrógeno' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'registro_automotor',
        type: 'select',
        label: 'Registro Automotor',
        description: 'ATR_PRT_ID - Registro donde se inscribe el vehículo',
        required: true,
        orderIndex: 17,
        help: 'Seleccione el registro automotor correspondiente',
        fieldConfig: JSON.stringify({
          loadFromEndpoint: true,
          endpoint: 'forms/dependent-options',
          requestBody: {
            endpoint: 'PAR_REGISTRO_AUTOMOTORES',
            parentValue: 'ALL',
          },
          valueField: 'codigo_registro',
          labelField: 'descripcion',
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({
          onChange: {
            action: 'populate',
            endpoint: 'forms/autocomplete',
            requestBody: {
              endpoint: 'PAR_REGISTRO_AUTOMOTORES',
              value: '{{ field_value }}',
              context: {
                table: 'par_registro_automotores',
                searchField: 'codigo_registro',
              },
            },
            fields: {
              registro_descripcion: 'descripcion',
            },
          },
        }),
      },
      {
        formId: 'vehicle-registration',
        name: 'registro_descripcion',
        type: 'text',
        label: 'Descripción del Registro',
        description:
          'L_PRT_PRT_DESCRIPCION - Descripción del registro automotor',
        readonly: true,
        orderIndex: 18,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'codigo_alta',
        type: 'select',
        label: 'Código de Alta',
        description: 'ATR_PCA_ID - Motivo del alta del vehículo',
        required: true,
        orderIndex: 19,
        fieldConfig: JSON.stringify({
          loadFromEndpoint: true,
          endpoint: 'forms/dependent-options',
          requestBody: {
            endpoint: 'PAR_CODIGOS_ALTAS',
            parentValue: 'ALL',
          },
          valueField: 'codigo_alta',
          labelField: 'descripcion',
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({
          onChange: {
            action: 'populate',
            endpoint: 'forms/autocomplete',
            requestBody: {
              endpoint: 'PAR_CODIGOS_ALTAS',
              value: '{{ field_value }}',
              context: {
                table: 'par_codigos_altas',
                searchField: 'codigo_alta',
              },
            },
            fields: {
              codigo_alta_descripcion: 'descripcion',
            },
          },
        }),
      },
      {
        formId: 'vehicle-registration',
        name: 'codigo_alta_descripcion',
        type: 'text',
        label: 'Descripción Código de Alta',
        description: 'L_PCA_PCA_DESCRIPCION - Descripción del código de alta',
        readonly: true,
        orderIndex: 20,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'numero_titulo',
        type: 'text',
        label: 'Número de Título',
        description: 'Número del título del automotor',
        required: true,
        orderIndex: 21,
        help: 'Número del título emitido por el registro',
        fieldConfig: JSON.stringify({
          maxLength: 20,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'fecha_emision_titulo',
        type: 'date',
        label: 'Fecha de Emisión del Título',
        description: 'Fecha de emisión del título del automotor',
        required: true,
        orderIndex: 22,
        defaultValue: '{{ today }}',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'observaciones_titulo',
        type: 'textarea',
        label: 'Observaciones del Título',
        description: 'Observaciones especiales sobre el título',
        placeholder: 'Observaciones especiales sobre la documentación...',
        orderIndex: 23,
        fieldConfig: JSON.stringify({
          maxLength: 500,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'cuit_propietario',
        type: 'cuit',
        label: 'CUIT del Propietario',
        description: 'CUIT del primer propietario del vehículo',
        placeholder: 'XX-XXXXXXXX-X',
        required: true,
        orderIndex: 24,
        help: 'CUIT de la persona física o jurídica propietaria',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({
          customValidation: 'validateCuit',
        }),
        eventsConfig: JSON.stringify({
          onValidation: {
            action: 'both',
            endpoint: 'forms/autocomplete',
            requestBody: {
              endpoint: 'SUJETOS_PASIVOS',
              value: '{{ field_value }}',
              context: { table: 'sujetos_pasivos', searchField: 'cuit' },
            },
            fields: {
              propietario_descripcion: 'razonSocial',
              tipo_documento: 'tipoDocumento',
              domicilio_fiscal: 'domicilioFiscal',
            },
            debounceTime: 500,
          },
        }),
      },
      {
        formId: 'vehicle-registration',
        name: 'propietario_descripcion',
        type: 'text',
        label: 'Datos del Propietario',
        description: 'Información del propietario obtenida del sistema',
        readonly: true,
        orderIndex: 25,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'porcentaje_propiedad',
        type: 'percentage',
        label: 'Porcentaje de Propiedad',
        description: 'Porcentaje de propiedad del vehículo',
        required: true,
        orderIndex: 26,
        defaultValue: '100',
        help: 'Porcentaje de propiedad (normalmente 100% para un solo propietario)',
        fieldConfig: JSON.stringify({
          min: 0,
          max: 100,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'tipo_vinculo',
        type: 'select',
        label: 'Tipo de Vínculo',
        description: 'VSO_PTV_ID - Tipo de vínculo entre sujeto y objeto',
        required: true,
        orderIndex: 27,
        defaultValue: 'PRO',
        help: 'Seleccione el tipo de vínculo según PAR_TIPOS_VINCULOS',
        fieldConfig: JSON.stringify({
          options: [
            { id: 'propietario', label: 'Propietario' },
            { id: 'usuario', label: 'Usuario' },
            { id: 'tenedor', label: 'Tenedor' },
            { id: 'poseedor', label: 'Poseedor' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'fecha_inicio_vinculo',
        type: 'date',
        label: 'Fecha Inicio Vínculo',
        description: 'VSO_FECHA_INICIO - Fecha de inicio del vínculo',
        required: true,
        orderIndex: 28,
        defaultValue: '{{ today }}',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'es_responsable',
        type: 'radio',
        label: '¿Será Responsable Tributario?',
        description:
          'VSO_RESPONSABLE - Indica si será responsable del pago de impuestos',
        required: true,
        orderIndex: 29,
        defaultValue: 'S',
        help: "Marque 'Sí' si el propietario será responsable tributario",
        fieldConfig: JSON.stringify({
          options: [
            { id: 'si', label: 'Sí' },
            { id: 'no', label: 'No' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'cilindrada',
        type: 'number',
        label: 'Cilindrada (cm³)',
        description: 'Cilindrada del motor en centímetros cúbicos',
        placeholder: '1600',
        orderIndex: 30,
        help: 'Cilindrada del motor según especificaciones técnicas',
        fieldConfig: JSON.stringify({
          min: 0,
          max: 10000,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'potencia',
        type: 'number',
        label: 'Potencia (HP)',
        description: 'Potencia del motor en caballos de fuerza',
        placeholder: '120',
        orderIndex: 31,
        help: 'Potencia del motor según especificaciones técnicas',
        fieldConfig: JSON.stringify({
          min: 0,
          max: 1000,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'peso_vehiculo',
        type: 'number',
        label: 'Peso del Vehículo (kg)',
        description: 'Peso del vehículo en kilogramos',
        placeholder: '1200',
        orderIndex: 32,
        help: 'Peso del vehículo sin carga',
        fieldConfig: JSON.stringify({
          min: 0,
          max: 50000,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'capacidad_carga',
        type: 'number',
        label: 'Capacidad de Carga (kg)',
        description: 'Capacidad máxima de carga en kilogramos',
        placeholder: '500',
        orderIndex: 33,
        help: 'Capacidad máxima de carga del vehículo',
        fieldConfig: JSON.stringify({
          min: 0,
          max: 50000,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'cantidad_ejes',
        type: 'number',
        label: 'Cantidad de Ejes',
        description: 'Número de ejes del vehículo',
        orderIndex: 34,
        defaultValue: '2',
        help: 'Cantidad total de ejes del vehículo',
        fieldConfig: JSON.stringify({
          min: 1,
          max: 10,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'cantidad_ruedas',
        type: 'number',
        label: 'Cantidad de Ruedas',
        description: 'Número total de ruedas del vehículo',
        orderIndex: 35,
        defaultValue: '4',
        help: 'Cantidad total de ruedas del vehículo',
        fieldConfig: JSON.stringify({
          min: 2,
          max: 20,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'tara',
        type: 'number',
        label: 'Tara (kg)',
        description: 'Peso en vacío del vehículo',
        orderIndex: 36,
        help: 'Peso del vehículo sin carga ni pasajeros',
        fieldConfig: JSON.stringify({
          min: 0,
          max: 50000,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'pbt',
        type: 'number',
        label: 'PBT - Peso Bruto Total (kg)',
        description: 'Peso bruto total máximo autorizado',
        orderIndex: 37,
        help: 'Peso bruto total máximo autorizado para el vehículo',
        fieldConfig: JSON.stringify({
          min: 0,
          max: 100000,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'documentos_presentados',
        type: 'multiselect',
        label: 'Documentos Presentados',
        description: 'Seleccione los documentos presentados para el alta',
        required: true,
        orderIndex: 38,
        help: 'Seleccione todos los documentos presentados para el alta',
        fieldConfig: JSON.stringify({
          options: [
            { id: 'cert_fabricacion', label: 'Certificado de Fabricación' },
            { id: 'factura_compra', label: 'Factura de Compra' },
            { id: 'cert_importacion', label: 'Certificado de Importación' },
            { id: 'cert_libre_deuda', label: 'Certificado Libre de Deuda' },
            { id: 'dni_propietario', label: 'DNI del Propietario' },
            { id: 'constancia_cuit', label: 'Constancia de CUIT' },
            { id: 'poder_notarial', label: 'Poder Notarial (si aplica)' },
            { id: 'formulario_13i', label: 'Formulario 13I' },
            { id: 'cert_gnc', label: 'Certificado GNC (si aplica)' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'verificacion_policial',
        type: 'radio',
        label: 'Verificación Policial',
        description: '¿Se realizó la verificación policial del vehículo?',
        required: true,
        orderIndex: 39,
        help: 'Estado de la verificación policial del vehículo',
        fieldConfig: JSON.stringify({
          options: [
            { id: 'verificado', label: 'Sí, verificado' },
            { id: 'no_verificado', label: 'No verificado' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'usuario_alta',
        type: 'text',
        label: 'Usuario de Alta',
        description: 'ATR_USUARIO_ALTA - Usuario que registra el alta',
        readonly: true,
        orderIndex: 40,
        help: 'Se completa automáticamente con el usuario actual del sistema',
        defaultValue: '{{ currentUser }}',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'fecha_alta_vehiculo',
        type: 'datetime',
        label: 'Fecha y Hora de Alta',
        description: 'ATR_FECHA_ALTA - Timestamp del alta del vehículo',
        readonly: true,
        orderIndex: 41,
        defaultValue: '{{ now }}',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-registration',
        name: 'observaciones',
        type: 'textarea',
        label: 'Observaciones Generales',
        description: 'Observaciones adicionales sobre el alta del vehículo',
        placeholder: 'Observaciones adicionales sobre el alta del vehículo...',
        orderIndex: 42,
        help: 'Registre cualquier información adicional relevante',
        fieldConfig: JSON.stringify({
          maxLength: 1000,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
    ];

    for (const fieldData of fields) {
      await this.formFieldRepository.create(fieldData);
    }
  }

  private async createVehicleTransferFields(): Promise<void> {
    const fields = [
      // SECCIÓN: Datos del Vehículo
      {
        formId: 'vehicle-transfer',
        name: 'patente',
        type: 'plate',
        label: 'Dominio (Patente)',
        description:
          'ATR_DOMINIO - Ingrese la patente del vehículo a consultar/transferir',
        placeholder: 'AB123CD',
        required: true,
        readonly: false,
        orderIndex: 1,
        help: 'Campo clave para la búsqueda del vehículo en el sistema',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({
          customValidation: 'validatePlate',
        }),
        eventsConfig: JSON.stringify({
          onValidation: {
            action: 'both',
            endpoint: 'automotor/consultar',
            fields: {
              modelo_rnpa: 'modelo_codigo',
              modelo_descripcion: 'modelo_descripcion',
              codigo_alta: 'codigo_alta',
              codigo_alta_descripcion: 'codigo_alta_desc',
              registro_automotor: 'registro_codigo',
              registro_descripcion: 'registro_desc',
              fecha_alta: 'fecha_alta_vehiculo',
              fecha_inicio: 'fecha_inicio_vigencia',
              fecha_fabricacion: 'anio_fabricacion',
              fecha_rige: 'fecha_rige_vigencia',
              origen_rnpa: 'origen',
              archivo_id: 'vehiculo_id',
            },
            debounceTime: 800,
          },
        }),
      },
      {
        formId: 'vehicle-transfer',
        name: 'tipo_vehiculo',
        type: 'hidden',
        label: 'Tipo de Vehículo',
        description: 'ATR_PTH_ID - Código interno del tipo de vehículo',
        readonly: true,
        orderIndex: 2,
        defaultValue: 'AUTO',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'modelo_rnpa',
        type: 'text',
        label: 'Modelo RNPA',
        description: 'ATR_PMO_ID - Identificación del modelo según RNPA',
        readonly: true,
        orderIndex: 3,
        help: 'Código del modelo asignado por el Registro Nacional de Propiedad del Automotor',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'modelo_descripcion',
        type: 'text',
        label: 'Descripción del Modelo',
        description:
          'L_PMO_PMO_DESCRIPCION - Descripción del modelo del vehículo',
        readonly: true,
        orderIndex: 4,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'codigo_alta',
        type: 'text',
        label: 'Código de Alta',
        description: 'ATR_PCA_ID - Código de alta del vehículo',
        readonly: true,
        orderIndex: 5,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'codigo_alta_descripcion',
        type: 'text',
        label: 'Descripción Código de Alta',
        description: 'L_PCA_PCA_DESCRIPCION - Descripción del código de alta',
        readonly: true,
        orderIndex: 6,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'registro_automotor',
        type: 'text',
        label: 'Registro Automotor',
        description: 'ATR_PRT_ID - Código del registro automotor',
        readonly: true,
        orderIndex: 7,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'registro_descripcion',
        type: 'text',
        label: 'Descripción Registro',
        description:
          'L_PRT_PRT_DESCRIPCION - Descripción del registro automotor',
        readonly: true,
        orderIndex: 8,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'fecha_alta',
        type: 'date',
        label: 'Fecha de Alta',
        description: 'ATR_FECHA_ALTA - Fecha de alta del registro del vehículo',
        readonly: true,
        orderIndex: 9,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'fecha_inicio',
        type: 'date',
        label: 'Fecha de Inicio de Vigencia',
        description: 'ATR_FECHA_INICIO - Fecha de inicio de vigencia',
        readonly: true,
        orderIndex: 10,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'fecha_fabricacion',
        type: 'number',
        label: 'Año de Fabricación',
        description: 'ATR_FECHA_FABRICACION - Año de fabricación del vehículo',
        placeholder: '2024',
        readonly: true,
        orderIndex: 11,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'fecha_rige',
        type: 'date',
        label: 'Fecha que Rige',
        description:
          'ATR_FECHA_RIGE - Fecha en que comienza a regir la vigencia',
        readonly: true,
        orderIndex: 12,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'origen_rnpa',
        type: 'radio',
        label: 'Origen RNPA',
        description: 'ATR_ORIGEN_RNPA - Origen del vehículo según RNPA',
        required: true,
        orderIndex: 13,
        help: 'Determina si el vehículo es de origen nacional o importado',
        fieldConfig: JSON.stringify({
          options: [
            { id: 'N', label: 'Nacional' },
            { id: 'I', label: 'Importado' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'marca_rnpa',
        type: 'text',
        label: 'Marca RNPA',
        description: 'ATR_ID_MARCA_RNPA - Código de marca según RNPA',
        placeholder: 'Código de marca',
        orderIndex: 14,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'marca_descripcion',
        type: 'text',
        label: 'Descripción Marca',
        description: 'Descripción de la marca del vehículo',
        readonly: true,
        orderIndex: 15,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'tipo_rnpa',
        type: 'text',
        label: 'Tipo RNPA',
        description: 'ATR_ID_TIPO_RNPA - Código de tipo según RNPA',
        orderIndex: 16,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'tipo_rnpa_descripcion',
        type: 'text',
        label: 'Descripción Tipo RNPA',
        description: 'Descripción del tipo de vehículo según RNPA',
        readonly: true,
        orderIndex: 17,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'modelo_rnpa_descripcion',
        type: 'text',
        label: 'Descripción Modelo RNPA',
        description: 'ATR_ID_MODELO_RNPA - Descripción del modelo según RNPA',
        readonly: true,
        orderIndex: 18,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'archivo_id',
        type: 'hidden',
        label: 'Número de Archivo',
        description: 'ATR_ID - Clave primaria del registro del vehículo',
        readonly: true,
        orderIndex: 19,
        defaultValue: '',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },

      // SECCIÓN: Propietarios
      {
        formId: 'vehicle-transfer',
        name: 'cuit_vendedor',
        type: 'cuit',
        label: 'CUIT del Propietario Actual',
        description:
          'CUIT del propietario que transfiere el vehículo (VSO_SPO_ID)',
        placeholder: 'XX-XXXXXXXX-X',
        required: true,
        orderIndex: 20,
        help: 'Debe corresponder a un registro válido en SUJETOS_PASIVOS',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({
          customValidation: 'validateCuit',
        }),
        eventsConfig: JSON.stringify({
          onValidation: {
            action: 'both',
            endpoint: 'contribuyente',
            fields: {
              vendedor_descripcion: 'nombre_completo',
            },
            debounceTime: 600,
          },
        }),
      },
      {
        formId: 'vehicle-transfer',
        name: 'vendedor_descripcion',
        type: 'text',
        label: 'Datos del Vendedor',
        description: 'Información del propietario actual obtenida del sistema',
        readonly: true,
        orderIndex: 21,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'cuit_comprador',
        type: 'cuit',
        label: 'CUIT del Nuevo Propietario',
        description: 'CUIT del nuevo propietario del vehículo',
        placeholder: 'XX-XXXXXXXX-X',
        required: true,
        orderIndex: 22,
        help: 'Debe corresponder a un registro válido en SUJETOS_PASIVOS',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({
          customValidation: 'validateCuit',
        }),
        eventsConfig: JSON.stringify({
          onValidation: {
            action: 'both',
            endpoint: 'contribuyente',
            fields: {
              comprador_descripcion: 'nombre_completo',
            },
            debounceTime: 600,
          },
        }),
      },
      {
        formId: 'vehicle-transfer',
        name: 'comprador_descripcion',
        type: 'text',
        label: 'Datos del Comprador',
        description: 'Información del nuevo propietario obtenida del sistema',
        readonly: true,
        orderIndex: 23,
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'porcentaje_propiedad',
        type: 'percentage',
        label: 'Porcentaje de Propiedad',
        description: 'Porcentaje de propiedad del vehículo (VSO_RESPONSABLE)',
        placeholder: '100',
        required: true,
        orderIndex: 24,
        help: 'Ingrese el porcentaje de propiedad que corresponde al nuevo propietario',
        fieldConfig: JSON.stringify({
          min: 0,
          max: 100,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'tipo_vinculo',
        type: 'select',
        label: 'Tipo de Vínculo',
        description: 'VSO_PTV_ID - Tipo de vínculo entre sujeto y objeto',
        required: true,
        orderIndex: 25,
        help: 'Seleccione el tipo de vínculo según PAR_TIPOS_VINCULOS',
        fieldConfig: JSON.stringify({
          options: [
            { id: 'PRO', label: 'Propietario' },
            { id: 'USU', label: 'Usuario' },
            { id: 'TEN', label: 'Tenedor' },
            { id: 'CON', label: 'Conductor Habitual' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'fecha_inicio_vinculo',
        type: 'date',
        label: 'Fecha Inicio Vínculo',
        description: 'VSO_FECHA_INICIO - Fecha de inicio del vínculo',
        required: true,
        orderIndex: 26,
        defaultValue: 'today',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'es_responsable',
        type: 'radio',
        label: '¿Será Responsable Tributario?',
        description:
          'VSO_RESPONSABLE - Indica si el nuevo propietario será responsable del pago de impuestos',
        required: true,
        orderIndex: 27,
        defaultValue: 'S',
        help: "Marque 'Sí' si el nuevo propietario será responsable tributario",
        fieldConfig: JSON.stringify({
          options: [
            { id: 'S', label: 'Sí' },
            { id: 'N', label: 'No' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'usuario_alta',
        type: 'text',
        label: 'Usuario de Alta',
        description: 'VSO_USUARIO_ALTA - Usuario que registra la transferencia',
        readonly: true,
        orderIndex: 28,
        defaultValue: '{{ currentUser }}',
        help: 'Se completa automáticamente con el usuario actual del sistema',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'fecha_alta_transferencia',
        type: 'datetime',
        label: 'Fecha y Hora de Alta',
        description:
          'VSO_FECHA_ALTA - Timestamp del registro de la transferencia',
        readonly: true,
        orderIndex: 29,
        defaultValue: '{{ now }}',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },

      // SECCIÓN: Datos de la Transferencia
      {
        formId: 'vehicle-transfer',
        name: 'fecha_transferencia',
        type: 'date',
        label: 'Fecha de Transferencia',
        description: 'TFA_FECHA - Fecha efectiva de la transferencia',
        required: true,
        orderIndex: 30,
        defaultValue: 'today',
        help: 'Fecha en que se efectúa la transferencia del vehículo',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'tipo_transferencia',
        type: 'select',
        label: 'Tipo de Transferencia',
        description:
          'P_TIPO_TRANSFERENCIA - Seleccione el motivo de la transferencia',
        required: true,
        orderIndex: 31,
        defaultValue: 'C',
        fieldConfig: JSON.stringify({
          options: [
            { id: 'C', label: 'Compraventa' },
            { id: 'D', label: 'Donación' },
            { id: 'H', label: 'Herencia' },
            { id: 'S', label: 'Incorporación a Sociedad' },
            { id: 'P', label: 'Permuta' },
            { id: 'J', label: 'Adjudicación Judicial' },
            { id: 'O', label: 'Otro' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'monto_operacion',
        type: 'money',
        label: 'Monto de la Operación',
        description: 'TFA_MONTO - Valor de la operación (si aplica)',
        placeholder: '0,00',
        orderIndex: 32,
        help: 'Ingrese el monto de la transacción si corresponde',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'moneda',
        type: 'select',
        label: 'Unidad Monetaria',
        description: 'TFA_PMA_ID - Unidad monetaria de la operación',
        orderIndex: 33,
        defaultValue: 'ARS',
        help: 'Seleccione la moneda según PAR_MONEDAS',
        fieldConfig: JSON.stringify({
          options: [
            { id: 'ARS', label: 'Pesos Argentinos' },
            { id: 'USD', label: 'Dólares Estadounidenses' },
            { id: 'EUR', label: 'Euros' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'numero_transferencia',
        type: 'number',
        label: 'Número de Transferencia',
        description: 'TFA_ID - Número de secuencia de la transferencia',
        readonly: true,
        orderIndex: 34,
        help: 'Se asigna automáticamente usando TFA_SEQ.NEXTVAL',
        fieldConfig: JSON.stringify({}),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },

      // SECCIÓN: Documentación y Observaciones
      {
        formId: 'vehicle-transfer',
        name: 'documentos_presentados',
        type: 'multiselect',
        label: 'Documentos Presentados',
        description: 'Seleccione los documentos que respaldan la transferencia',
        orderIndex: 35,
        help: 'Seleccione todos los documentos presentados para la transferencia',
        fieldConfig: JSON.stringify({
          options: [
            { id: 'titulo', label: 'Título del Vehículo' },
            { id: 'cedula_verde', label: 'Cédula Verde' },
            { id: 'cedula_azul', label: 'Cédula Azul' },
            { id: 'dni_vendedor', label: 'DNI del Vendedor' },
            { id: 'dni_comprador', label: 'DNI del Comprador' },
            { id: 'formulario_08', label: 'Formulario 08' },
            { id: 'libre_deuda', label: 'Certificado Libre de Deuda' },
            { id: 'contrato_compraventa', label: 'Contrato de Compraventa' },
            { id: 'poder_notarial', label: 'Poder Notarial (si aplica)' },
            {
              id: 'certificado_verificacion',
              label: 'Certificado de Verificación Policial',
            },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'situacion_especial',
        type: 'select',
        label: 'Situación Especial',
        description:
          'Situación especial del vehículo (VSE - VINCULOS_SITUACION_ESPECIAL)',
        orderIndex: 36,
        defaultValue: 'NORMAL',
        help: 'Indique si el vehículo tiene alguna situación especial registrada',
        fieldConfig: JSON.stringify({
          options: [
            { id: 'NORMAL', label: 'Normal' },
            { id: 'EMBARGO', label: 'Embargado' },
            { id: 'INHIBICION', label: 'Inhibición' },
            { id: 'PRENDA', label: 'Prenda' },
            { id: 'SECUESTRO', label: 'Secuestro Judicial' },
            { id: 'OTRO', label: 'Otra Situación' },
          ],
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
      {
        formId: 'vehicle-transfer',
        name: 'observaciones',
        type: 'textarea',
        label: 'Observaciones',
        description:
          'TFA_OBSERVACIONES - Información adicional relevante para la transferencia',
        placeholder: 'Observaciones adicionales sobre la transferencia...',
        orderIndex: 37,
        help: 'Registre cualquier información adicional relevante para la transferencia',
        fieldConfig: JSON.stringify({
          maxLength: 500,
        }),
        validationConfig: JSON.stringify({}),
        eventsConfig: JSON.stringify({}),
      },
    ];

    for (const fieldData of fields) {
      await this.formFieldRepository.create(fieldData);
    }
  }
}
